### PR TITLE
Setgame-idle command

### PR DESCRIPTION
**Pull request by lavender-sys**
This command allows you to set the bot to idle and set the game.

### CODE REVIEW

**Comment by Dougley** [comment]
You're forgetting a + between `suffix` and `"idle!"` Else it's fine

**Comment by lavender-sys** [comment]
Fixed! @SteamingMutt

**Comment by Dougley** [comment]
It seems you've also forgot the function closing `)` at the end of the `bot.sendMessage` function

**Comment by lavender-sys** [comment]
Fixed! @SteamingMutt

**Pull request merged**
